#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <locale.h>
int i,j,k,l,m,Linha,Coluna,aux,val,ChanceGolExtra,GolTimeA,GolTimeB,AmplitudeGolsA,AmplitudeGolsB,TimeMaiorSomaA,TimeMaiorSomaB,TimeMaiorPlacarA,TimeMaiorPlacarB,RodadaMaiorSoma,MaiorSoma=0,MaiorGoleada=0,TimeMaiorGoleadaA,TimeMaiorGoleadaB,GolMaiorGoleadaA,GolMaiorGoleadaB,RodadaMaiorGoleada,a[380],b[380],Pontos[20],v[20],e[20],d[20],sg[20],gp[20],gc[20],Posicao[20],LogColuna[10],Vantagem[9],LogVantagem[9],PartidasPadrao[19][20],PartidasSorteadas[19][20];
char Forma[20][6],AuxForma[2],*nome[]={"Flamengo", "Santos", "Atletico-MG","Palmeiras","Botafogo","Fluminense","Cuiaba","Sao Paulo","Juventude","Athletico-PR","Atletico-GO","RB Bragrantino","Corinthians","America-MG","Fortaleza","Ceara","Avai","Goias","Coritiba","Internacional"};
void OrganizarPartidas()
{
    k=0;
    for(i=0;i<20;i++)
    {
        for(j=0;j<20;j++)
        {
            if(i!=j&&i<j)
            {
                a[k]=i;
                b[k]=j;
                k++;
            }
        }
    }
    k=18;
    for(i=0;i<19;i++)
    {
        PartidasPadrao[i][0]=a[k];
        PartidasPadrao[i][1]=b[k];
        k--;
    }
    for(i=0;i<19;i++)
    {
        k=PartidasPadrao[i][1]+1;
        if(k==20)
            k=0;
        for(j=3;j<=19;j+=2)
        {
            val=0;
            for(l=0;l<j;l++)
            {
                if(k==PartidasPadrao[i][l])
                {
                    val=1;
                    l=j;
                }
            }
            if(val==0)
            {
                PartidasPadrao[i][j]=k;
            }
            k++;
            if(val==1)
                j-=2;
            if(k==20)
                k=0;
        }
        k=PartidasPadrao[i][19]+1;
        if(k==20)
            k=0;
        for(j=18;j>=2;j-=2)
        {
            val=0;
            for(l=0;l<j;l++)
            {
                if(PartidasPadrao[i][l]!=-1)
                    if(k==PartidasPadrao[i][l]||k==PartidasPadrao[i][l+2])
                    {
                        val=1;
                        l=j;
                    }
            }
            if(val==0)
            {
                PartidasPadrao[i][j]=k;
            }
            k++;
            if(val==1)
                j+=2;
            if(k==20)
                k=0;
        }
    }
    for(i=0;i<19;i++)
    {
        Linha=rand()%19;
        k=0;
        for(j=0;j<10;j++)
            LogColuna[j]=-1;
        if(PartidasPadrao[Linha][0]==-1)
            i--;
            else
            {
                for(j=0;j<=18;j+=2)
                {
                    do
                    {
                        val=0;
                        Coluna=rand()%19;
                        for(l=0;l<10;l++)
                            if(Coluna==LogColuna[l])
                            {
                                val=1;
                                l=20;
                            }
                    }
                    while(val==1||Coluna%2!=0);
                    LogColuna[k]=Coluna;
                    k++;
                    PartidasSorteadas[i][j]=PartidasPadrao[Linha][Coluna];
                    PartidasSorteadas[i][j+1]=PartidasPadrao[Linha][Coluna+1];
                }
                PartidasPadrao[Linha][0]=-1;
            }
    }
    k=0;
    for(i=0;i<38;i++)
    {
        for(j=0;j<=18;j+=2)
        {
            if(i<19)
            {
                a[k]=PartidasSorteadas[i][j];
                b[k]=PartidasSorteadas[i][j+1];    
            }
            else
            {
                b[k]=PartidasSorteadas[i-19][j];
                a[k]=PartidasSorteadas[i-19][j+1];
            }
            k++;
        }
    }
}
void ExibirPlacares()
{
    for(i=0;i<20;i++)
    {
        Pontos[i]=0;
        Posicao[i]=i;
        v[i]=0;
        e[i]=0;
        d[i]=0;
        gp[i]=0;
        gc[i]=0;
        sg[i]=0;
    }
    for(i=0;i<9;i++)
        LogVantagem[i]=-1;
    for(i=0;i<9;i++)
    {
        val=0;
        Vantagem[i]=rand()%20;
        for(j=0;j<9;j++)
            if(Vantagem[i]==LogVantagem[j])
            {
                i--;
                j=9;
                val=1;
            }
        if(val==0)
        {
            LogVantagem[i]=Vantagem[i];
        }
    }
    k=0;
    for(i=0;i<38;i++)
    {
        printf("-------------------------------\n            Rodada %d\n-------------------------------\n",i+1);
        for(j=0;j<10;j++)
        {
            AmplitudeGolsA=rand()%20;
            AmplitudeGolsB=rand()%20;
            if(AmplitudeGolsA>17&&AmplitudeGolsB>17)
            {
                GolTimeA=rand()%6;
                GolTimeB=rand()%6;
            }
            else if(AmplitudeGolsA>17&&AmplitudeGolsB<=17)
            {
                GolTimeA=rand()%6;
                GolTimeB=rand()%3;
            }
            else if(AmplitudeGolsB>17&&AmplitudeGolsA<=17)
            {
                GolTimeB=rand()%6;
                GolTimeA=rand()%3;
            }
            else
            {
                GolTimeA=rand()%3;
                GolTimeB=rand()%3;
            }
            if(AmplitudeGolsA==0)
                GolTimeA++;
            if(AmplitudeGolsB==0)
                GolTimeB++;
            for(l=0;l<9;l++)
            {
                if(a[k]==Vantagem[l])
                {
                    if(l>=0&&l<=4)
                    {
                        ChanceGolExtra=rand()%2;
                        if(ChanceGolExtra==0)
                            GolTimeA++;
                    }
                    else if(l>=3&&l<=5)
                    {
                        ChanceGolExtra=rand()%10;
                        if(ChanceGolExtra==0)
                            GolTimeA++;
                    }
                    if(l>=6&&l<=8)
                    {
                        if(GolTimeA>0)
                        {
                            ChanceGolExtra=rand()%2;
                            if(ChanceGolExtra==0)
                                GolTimeA--;
                        }
                    }
                }
                if(b[k]==Vantagem[l])
                {
                    if(l>=0&&l<=2)
                    {
                        ChanceGolExtra=rand()%2;
                        if(ChanceGolExtra==0)
                            GolTimeB++;
                    }
                    else if(l>=3&&l<=5)
                    {
                        ChanceGolExtra=rand()%10;
                        if(ChanceGolExtra==0)
                            GolTimeB++;
                    }
                    if(l>=6&&l<=8)
                    {
                        if(GolTimeB>0)
                        {
                            ChanceGolExtra=rand()%2;
                            if(ChanceGolExtra==0)
                                GolTimeB--;
                        }
                    }
                }
            }
            if(GolTimeA-GolTimeB>MaiorGoleada||GolTimeB-GolTimeA>MaiorGoleada)
            {
                TimeMaiorGoleadaA=a[k];
                TimeMaiorGoleadaB=b[k];
                GolMaiorGoleadaA=GolTimeA;
                GolMaiorGoleadaB=GolTimeB;
                RodadaMaiorGoleada=i;
                if(GolTimeA-GolTimeB>MaiorGoleada)
                    MaiorGoleada=GolTimeA-GolTimeB;
                    else
                        MaiorGoleada=GolTimeB-GolTimeA;
            }
            if(GolTimeA+GolTimeB>MaiorSoma)
            {
                TimeMaiorPlacarA=a[k];
                TimeMaiorPlacarB=b[k];
                TimeMaiorSomaA=GolTimeA;
                TimeMaiorSomaB=GolTimeB;
                MaiorSoma=GolTimeA+GolTimeB;
                RodadaMaiorSoma=i;
            }
            if(GolTimeA>GolTimeB)
            {
                Pontos[a[k]]+=3;
                v[a[k]]++;
                d[b[k]]++;
                if(i>32)
                {
                    Forma[a[k]][i-33]='V';
                    Forma[b[k]][i-33]='D';
                }
            }
            else if(GolTimeA<GolTimeB)
            {
                Pontos[b[k]]+=3;
                v[b[k]]++;
                d[a[k]]++;
                if(i>32)
                {
                    Forma[a[k]][i-33]='D';
                    Forma[b[k]][i-33]='V';
                }
            }
            else
            {
                Pontos[a[k]]++;
                Pontos[b[k]]++;
                e[a[k]]++;
                e[b[k]]++;
                if(i>32)
                {
                    Forma[a[k]][i-33]='E';
                    Forma[b[k]][i-33]='E';
                }
            }
            gp[a[k]]+=GolTimeA;
            gp[b[k]]+=GolTimeA;
            gc[a[k]]+=GolTimeB;
            gc[b[k]]+=GolTimeA;
            printf("%14s %d-%d %s\n",nome[a[k]],GolTimeA,GolTimeB,nome[b[k]]);
            k++;
        }
    }
}
void OrganizarRanking()
{
    for(i=0;i<20;i++)
        sg[i]=gp[i]-gc[i];
    for(i=0;i<20;i++)
        if(Pontos[i]<Pontos[i-1]||Pontos[i]==Pontos[i-1]&&v[i]<v[i-1]||Pontos[i]==Pontos[i-1]&&v[i]==v[i-1]&&sg[i]<sg[i-1]||Pontos[i]==Pontos[i-1]&&v[i]==v[i-1]&&sg[i]==sg[i-1]&&gp[i]<gp[i-1])
        {
            aux=Pontos[i];
            Pontos[i]=Pontos[i-1];
            Pontos[i-1]=aux;
            aux=Posicao[i];
            Posicao[i]=Posicao[i-1];
            Posicao[i-1]=aux;
            aux=v[i];
            v[i]=v[i-1];
            v[i-1]=aux;
            aux=e[i];
            e[i]=e[i-1];
            e[i-1]=aux;
            aux=d[i];
            d[i]=d[i-1];
            d[i-1]=aux;
            aux=gp[i];
            gp[i]=gp[i-1];
            gp[i-1]=aux;
            aux=gc[i];
            gc[i]=gc[i-1];
            gc[i-1]=aux;
            aux=sg[i];
            sg[i]=sg[i-1];
            sg[i-1]=aux;
            for(j=0;j<5;j++)
            {
                AuxForma[0]=Forma[i][j];
                Forma[i][j]=Forma[i-1][j];
                Forma[i-1][j]=AuxForma[0];
            }
            i=0;
        }
}
void ExibirRanking()
{
    k=0;
    printf("                   __________________________________________\n   ,--------------| Pt |  V |  E |  D | GP | GC | SG | Forma |\n");
    for(i=19;i>=0;i--)
    {
        printf("%2dº|%-14s| %2d | %2d | %2d | %2d |%3d |%3d |%3d | %c%c%c%c%c |\n",k+1,nome[Posicao[i]],Pontos[i],v[i],e[i],d[i],gp[i],gc[i],sg[i],Forma[i][0],Forma[i][1],Forma[i][2],Forma[i][3],Forma[i][4]);
        k++;
    }
    printf("   '---------------------------------------------------------'\n     Maior goleada: %14s %d x %d %s (rodada %d)\nJogo com mais gols: %14s %d x %d %s (rodada %d)",nome[TimeMaiorGoleadaA],GolMaiorGoleadaA,GolMaiorGoleadaB,nome[TimeMaiorGoleadaB],RodadaMaiorGoleada+1,nome[TimeMaiorPlacarA],TimeMaiorSomaA,TimeMaiorSomaB,nome[TimeMaiorPlacarB],RodadaMaiorSoma+1);
}
int main()
{
    srand(time(NULL));
    setlocale(LC_ALL,"");
    OrganizarPartidas();
    ExibirPlacares();
    OrganizarRanking();
    ExibirRanking();
    return 0;
}